services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: sheet-php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - postgres

    nginx:
        image: nginx:latest
        container_name: sheet-nginx
        ports:
            - "8089:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    node:
        image: node:20-slim
        container_name: sheet-node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: ["sh", "-c", "npm ci && npm run dev -- --host"]
        ports:
            - "5173:5173"
        depends_on:
            - app
        profiles:
            - dev

    postgres:
        image: postgres:15
        container_name: sheet-postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
